In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# however MLR is the poorest ML algorithm with least accuracy

In [ ]:
#used when there are  multiple dependent variables

In [2]:
data=pd.read_csv('hire.csv')
data.head()

Percentage  Backlog  Internship  First_Round  Communication_Skills  Hired  \
0        81.0        0           1         75.0                  80.0      1   
1        70.0        0           3         87.0                  70.0      1   
2        81.0        2           3         75.0                  67.0      0   
3        56.0        3           3         42.0                  76.0      0   
4        74.0        4           3         82.0                  75.0      1   

   Unnamed: 6  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [3]:
real_x=data.iloc[:,0:5].values
real_x

array([[ 81.,   0.,   1.,  75.,  80.],
       [ 70.,   0.,   3.,  87.,  70.],
       [ 81.,   2.,   3.,  75.,  67.],
       ...,
       [ 65.,   2.,   1.,  60.,  70.],
       [100.,   5.,   3.,  88.,  88.],
       [100.,   8.,   1.,  88.,  88.]])

In [4]:
real_y=data.iloc[:,5].values
real_y

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [5]:
training_x,test_x,training_y,test_y=train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [6]:
training_x

array([[ 50. ,   3. ,   1. ,  40. ,  50. ],
       [ 92. ,   0. ,   6. ,  80. ,  88. ],
       [ 68.2,   2. ,   1. ,  50. ,  60. ],
       ...,
       [ 50. ,   4. ,   2. ,  60. , 100. ],
       [ 72. ,   1. ,   4. ,  70. ,  80. ],
       [ 65. ,   5. ,   4. ,  23. ,  45. ]])

In [7]:
test_x

array([[ 82.  ,   0.  ,   2.  ,  63.  ,  73.  ],
       [ 83.  ,   1.  ,   2.  ,  62.  ,  89.  ],
       [ 59.  ,   8.  ,   2.  ,  75.  ,  65.  ],
       [ 78.  ,   1.  ,   1.  ,  70.  ,  75.  ],
       [ 60.  ,   0.  ,   3.  ,  66.  ,  62.  ],
       [ 90.  ,   0.  ,   3.  ,  80.  ,  80.  ],
       [ 67.  ,   1.  ,   2.  ,  62.  ,  73.  ],
       [ 85.  ,   3.  ,   2.  ,  75.  ,  75.  ],
       [ 85.  ,   0.  ,   4.  ,  85.  ,  90.  ],
       [ 92.  ,   0.  ,   4.  ,  89.  ,  78.  ],
       [ 56.  ,   3.  ,   1.  ,  70.  ,  59.  ],
       [ 85.  ,   3.  ,   4.  ,  82.  ,  75.  ],
       [ 67.  ,   4.  ,   6.  ,  60.  ,  55.  ],
       [ 80.  ,   1.  ,   2.  ,  70.  ,  80.  ],
       [ 62.  ,   7.  ,   1.  ,  77.  ,  67.  ],
       [ 71.6 ,   0.  ,   4.  ,  75.  ,  85.  ],
       [ 80.  ,   2.  ,   4.  ,  80.  ,  80.  ],
       [ 58.  ,   5.  ,   2.  ,  60.  ,  70.  ],
       [ 30.  ,   8.  ,   0.  ,  20.  ,  35.  ],
       [ 73.  ,   0.  ,   2.  ,  70.  ,  72.  ],
       [ 70.  ,   3.

In [8]:
training_y

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0]

In [9]:
test_y

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [11]:
mlr=LinearRegression()
mlr.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
pred_y=mlr.predict(test_x)
pred_y

array([ 0.65443056,  0.71481971,  0.08944341,  0.61984327,  0.46205042,
        0.92157283,  0.48347166,  0.62301768,  1.02008541,  1.01582016,
        0.23578769,  0.72309535,  0.26024725,  0.69236441,  0.17452629,
        0.80670004,  0.76187725,  0.16185629, -0.82360153,  0.6386183 ,
        0.65608014,  0.39486195,  0.7219636 ,  0.44553584,  0.59759224,
        0.7051819 ,  0.97223032,  0.44862992,  0.33515917,  0.76120143,
        0.30088546,  0.67464587,  0.26216849,  0.76137896,  0.41768422,
        0.51116565,  0.95618422,  0.61796379,  1.00746293,  0.93268868,
        1.03133782,  0.62145072,  0.63462593,  0.36661366,  0.52165228,
        0.49220077,  0.79735918,  0.81597615,  0.63472049,  0.70571545,
        0.67828263,  0.6812553 ,  0.48269749,  0.61579124,  0.29408633,
        0.80145488,  0.72254444,  0.95683884,  0.36292553,  0.09763276,
        0.62525445,  0.75134537,  0.60683954,  1.03837182,  0.65308651,
       -0.05557154,  1.01164184,  0.82393589,  1.05145362,  0.72

In [13]:
test_y

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)